### ISSUE TITLE
fix "expand" arrow for work section

### ISSUE THREAD

**Issue by greglinch** [cordawso/Final-project#20]
When expanded and after clicking on a news organization under it, the arrow becomes a solid color without any indication that it can be collapsed:

<img width="981" alt="Screen Shot 2019-04-24 at 11 02 42 PM" src="https://user-images.githubusercontent.com/327783/56707002-283ad900-66e5-11e9-9fa5-333829356070.png">

When you hover it during that instance, it turns white. If you click it again, it closes as expected but then the arrow disappears.

**Comment by cordawso** [comment]
I've been working on this for some time now and finally put in a request on a WordPress help forum. Here's what I wrote: [https://en.forums.wordpress.com/topic/customization-to-add-arrow-to-collapse-menu/](url)

I'm a little pessimistic about trying to work with this state-based selector ("aria-expanded") It seems...not well liked, especially from an accessibility standpoint. [https://www.heydonworks.com/article/aria-controls-is-poop](url)

**Comment by greglinch** [comment]
@cordawso Did you see the reply noting the proper forum to ask that? Just wanted to make sure you did. 

Instead of trying to get it work as is, you might want to try simplifying it. For example, just using a arrow image and then jQuery `onClick` to rotate the image indicating "open" and "closed" depending on the rotation in CSS.

**Comment by cordawso** [comment]
This is fixed — see a new commit in the styles.css file.
