### ISSUE TITLE
Consider adding "share" buttons

### ISSUE THREAD

**Issue by sidlowsh** [cordawso/Final-project#3]
Since this is a portfolio site, you may want to find ways to encourage people to re-share your content. I've seen some plug-ins that allow you to add social sharing icons (for Twitter, Facebook, etc.), that you may want to look into.

**Comment by cordawso** [comment]
Ah that's a good idea. I'll definitely look into doing that, perhaps I'll add some share icons next to the buttons at the bottom of the articles. Thanks!
