### ISSUE TITLE
Update Hyperlink CSS

### ISSUE THREAD

**Issue by sidlowsh** [cordawso/Final-project#5]
I love the clean look and feel of this site's design! One thing that stood out to me as distracting was the CSS of the hyperlinks within the body copy of the stories. The bold text makes the eye jump to external links, which seems to break up the flow of the story narrative. Consider changing this CSS to make the links underlined but not bold, or something similar.

**Comment by lexinal** [comment]
I also wanted to comment on the hyperlinks of your site. I would consider making a resource page and addressing several of these sources on a new page. I think omitting the bold hyperlinks will add to the simplicity of your page.

**Comment by cordawso** [comment]
Thanks for the feedback — I think I'd like to keep the bold to encourage clicking through to the links. It gives people incentive to see what else is out there that I've done.
